### ISSUE TITLE
WGS SV Annotation Workflow Default Config

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#107]
**Issue**
The workflow `wgs_sv_annotation` has as default mapping and SV calling respectively `bwa` and `delly2`. But during the start step call the step required config is not added to the configuration and thus it overwrites the information  local config.

Add step command:
```
snappy-start-step --step wgs_sv_annotation
```
_Relevant parts of config:_
```
  ngs_mapping:
    tools:
      dna:
      - dragen

  variant_calling:
    tools:
    - dragen
    - 
  ...

  wgs_sv_calling:
    tools:
      dna:
      - dragen
```

_Error message:_
```
03-01 14:02 snakemake.logging WARNING  Building DAG of jobs...
MissingInputException in line 73 of ...snappy-pipeline/snappy_pipeline/workflows/wgs_sv_annotation/Snakefile:
Missing input files for rule wgs_sv_annotation_vcf_sv_filter:
...wgs_sv_calling/work/dragen.dragen.merge_genotypes/out/dragen.dragen.merge_genotypes.bcf.csi
...variant_calling/work/dragen.gatk_hc.NA12878-N1-DNA1-WGS1/out/dragen.gatk_hc.NA12878-N1-DNA1-WGS1.vcf.gz.tbi
...wgs_sv_calling/work/dragen.dragen.merge_genotypes/out/dragen.dragen.merge_genotypes.bcf
...variant_calling/work/dragen.gatk_hc.NA12878-N1-DNA1-WGS1/out/dragen.gatk_hc.NA12878-N1-DNA1-WGS1.vcf.gz
```

**Expected behavior**
Remove tools from default configuration and add entries to local config via `snappy-start-step` command.

**Additional context**
Default configuration from class: https://github.com/bihealth/snappy-pipeline/blob/master/snappy_pipeline/workflows/wgs_sv_annotation/__init__.py#L81
