### ISSUE TITLE
 WGS CNV Annotation Workflow Default Config 

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#108]
**Issue**
The workflow `wgs_cnv_annotation` has as default mapping and CNV calling respectively `bwa` and `erds_sv2`. But during the start step call the step required config is not added to the configuration and thus it overwrites the information  local config.
_Note:_ Error probably extends to `wgs_cnv_calling` as well. 

Add step command:
```
snappy-start-step --step wgs_cnv_annotation
```
_Relevant parts of config:_
```
  ngs_mapping:
    tools:
      dna:
      - dragen

  variant_calling:
    tools:
    - dragen
    - 
  ...

  wgs_cnv_calling:
    tools:
      - dragen
```

_Error message:_
```
3-01 14:43 snakemake.logging WARNING  Building DAG of jobs...
MissingInputException in line 73 of .../snappy-pipeline/snappy_pipeline/workflows/wgs_cnv_annotation/Snakefile:
Missing input files for rule wgs_cnv_annotation_vcf_cnv_filter:
...wgs_cnv_calling/work/dragen.erds_sv2.merge_genotypes/out/dragen.erds_sv2.merge_genotypes.vcf.gz
...wgs_cnv_calling/work/dragen.erds_sv2.merge_genotypes/out/dragen.erds_sv2.merge_genotypes.vcf.gz.tbi
```

**Expected behavior**
Remove tools from default configuration and add entries to local config via `snappy-start-step` command.

**Additional context**
Default configuration from class: https://github.com/bihealth/snappy-pipeline/blob/master/snappy_pipeline/workflows/wgs_cnv_annotation/__init__.py#L81
