### ISSUE TITLE
gCNV pipeline not independent from XHMM configuration in targeted_seq_cnv_annotation

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#123]
**Issue**
Build library dictionary in `VcfCnvFilterStepPart` depends on configuration from 'xhmm', it should also work if only 'gcnv' is set.

Required config even if just gCNV is used:
```
          targeted_seq_cnv_calling:
            tools:
              - gcnv
            xhmm:
              path_target_interval_list_mapping:
                - pattern: "Agilent SureSelect Human All Exon V6.*"
                  name: "Agilent_SureSelect_Human_All_Exon_V6"
                  path: /path/to/Agilent/SureSelect_Human_All_Exon_V6_r2/GRCh37/Exons.bed
          ...

          targeted_seq_cnv_annotation:
            path_ngs_mapping: ../ngs_mapping
            path_targeted_seq_cnv_calling: ../targeted_seq_cnv_calling
            tools_ngs_mapping:
            - bwa
            tools_targeted_seq_cnv_calling:
            - gcnv
```

Code:
```
    @dictify
    def _build_ngs_library_to_kit(self):
        xhmm_config = DictQuery(self.w_config).get("step_config/targeted_seq_cnv_calling/xhmm")
        if not xhmm_config["path_target_interval_list_mapping"]:
            # No mapping given, we will use the "default" one for all.
            for donor in self.parent._all_donors():
            for donor in self.parent.all_donors():
                if donor.dna_ngs_library:
                    yield donor.dna_ngs_library.name, "default"
   ...

```
https://github.com/bihealth/snappy-pipeline/blob/master/snappy_pipeline/workflows/targeted_seq_cnv_annotation/__init__.py#L113
