### ISSUE TITLE
gCNV pipeline not independent from XHMM configuration in targeted_seq_cnv_export

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#124]
**Issue**
Build library dictionary in `VarfishAnnotatorAnnotateStepPart` depends on configuration from 'xhmm', it should also work if only 'gcnv' is set.

Required config even if just gCNV is used:
```
          targeted_seq_cnv_calling:
            tools:
              - gcnv
            xhmm:
              path_target_interval_list_mapping:
                - pattern: "Agilent SureSelect Human All Exon V6.*"
                  name: "Agilent_SureSelect_Human_All_Exon_V6"
                  path: /path/to/Agilent/SureSelect_Human_All_Exon_V6_r2/GRCh37/Exons.bed
          ...
  
          targeted_seq_cnv_export:
            path_ngs_mapping: ../ngs_mapping
            path_targeted_seq_cnv_annotation: ../targeted_seq_cnv_annotation
       ...
```

Code:
```

    @dictify
    def _build_ngs_library_to_kit(self):
        xhmm_config = DictQuery(self.w_config).get("step_config/targeted_seq_cnv_calling/xhmm")
        if not xhmm_config["path_target_interval_list_mapping"]:
            # No mapping given, we will use the "default" one for all.
            for donor in self.parent.all_donors():
                if donor.dna_ngs_library:
                    yield donor.dna_ngs_library.name, "default"
        # Build mapping.
        regexes = {
        ...

```
https://github.com/bihealth/snappy-pipeline/blob/master/snappy_pipeline/workflows/targeted_seq_cnv_export/__init__.py#L117
