### ISSUE TITLE
Inconsistent configuration usage in snappy_pipeline.workflows.variant_checking

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#137]
**Issue**
Inconsistent configuration usage. In the default configuration, `tools_ngs_mapping`  is defined as a list:
```
step_config:
  variant_checking:
    tools_ngs_mapping: []  # optional, copied from ngs mapping config
``` 
...but it is set and used as dictionary if not provided by user:
```
   def __init__(self, workflow, config, config_lookup_paths, config_paths, workdir):
        ...
        # Copy over "tools" setting from ngs_mapping/variant_calling if not set here
        if not self.config["tools_ngs_mapping"]:
            self.config["tools_ngs_mapping"] = self.w_config["step_config"]["ngs_mapping"]["tools"]
        ...

    def _yield_peddy_results(self):

                for path in self.sub_steps["peddy"].get_output_files("run").values():
                    yield from expand(
                        path,
                        mapper=self.config["tools_ngs_mapping"]["dna"],   ### <<<<<<< HERE >>>>>>>>>>>
                        var_caller=self.config["tools_variant_calling"],
                        index_ngs_library=[pedigree.index.dna_ngs_library.name],
                    )

```
...as it is how it is defined in `ngs_mapping` default configuration:
```
step_config:
  ngs_mapping:
    # Aligners to use for the different NGS library types
    tools:
      dna: []      # Required if DNA analysis; otherwise, leave empty. Example: 'bwa'.
      rna: []      # Required if RNA analysis; otherwise, leave empty. Example: 'star'.
      dna_long: [] # Required if long-read mapper used; otherwise, leave empty. Example: 'ngmlr'.
```

**To replicate**
Define `tools_ngs_mapping` in the `.snappy_pipeline/config.yaml`, and execute the workflow.
```
  variant_checking:
    path_variant_calling: ../variant_calling
    tools_ngs_mapping: ["bwa"]
    tools_variant_calling: ["gatk_hc", "freebayes"]
    tools: ['peddy']
```
Expected error:
```
TypeError in line 39 of /<PATH>/snappy-pipeline/snappy_pipeline/workflows/variant_checking/Snakefile:
list indices must be integers or slices, not str
  File "/<PATH>/snappy-pipeline/snappy_pipeline/workflows/variant_checking/Snakefile", line 39, in <module>
  File "/<PATH>/snappy-pipeline/snappy_pipeline/utils.py", line 22, in patched
  File "/<PATH>/snappy-pipeline/snappy_pipeline/workflows/variant_checking/__init__.py", line 182, in get_result_files
  File "/<PATH>/snappy-pipeline/snappy_pipeline/workflows/variant_checking/__init__.py", line 196, in _yield_peddy_results
```
