### ISSUE TITLE
Update `jannovar` env

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#146]
**Task**
- Pin version `jannovar-cli==0.36`

_Note_: Transferred from #143 

**Important**
It will have implications to `cubit` | `config.yaml` as internally we only have files for `v0.36` available: 
```
  variant_calling:
    ...
    jannovar_statistics:
      path_ser: PATH/cubit/20.05/static_data/app_support/Jannovar/0.34/hg19_refseq_curated.ser
```
