### ISSUE TITLE
ngs_mapping crashes for target_cov_report

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/snappy-pipeline#164]
**Describe the bug**
Using `ngs_mapping` for WGS data appears to crash the step.

**To Reproduce**
1. Configure with the config.yaml and sample sheet from below.
3. Run snakemake to generate `target_cov_report.txt.md5`
4. See it crash because no input file is used for this step.

```
# config.yaml snippet
    target_coverage_report:
      path_target_interval_list_mapping:
      - name: "__default__"
        path: /fast/projects/cubit/current/static_data/exon_list/ENSEMBL/75/GRCh37/ENSEMBL_75.bed
```

```
# sample sheet snippet
[Metadata]
schema  germline_variants
schema_version  v1

[Custom Fields]
key     annotatedEntity docs    type    minimum maximum unit    choices pattern
batchNo bioEntity       Batch No.       integer .       .       .       .       .
familyId        bioEntity       Family  string  .       .       .       .       .
projectUuid     bioEntity       Project UUID    string  .       .       .       .       .
libraryKit      ngsLibrary      Enrichment kit  string  .       .       .       .       .

[Data]
familyId        patientName     fatherName      motherName      sex     isAffected      libraryType     folderName      batchNo hpoTerms        projectUuid     seqPlatform     libraryKit
FAM_Case_1      Case_1_index    Case_1_father   Case_1_mother   M       Y       WGS     NA12386 1       .       ca9211f1-0624-4537-8f3f-439a9a471a79    ILLUMINA        Illumina PCR-free
FAM_Case_1      Case_1_father   0       0       M       N       WGS     NA12399 1       .       ca9211f1-0624-4537-8f3f-439a9a471a79    ILLUMINA        Illumina PCR-free
```

**Expected behavior**
The target coverage reports should be generated for genomes and then summarized.

**Additional context**
N/A
