### ISSUE TITLE
Change default for depth of coverage track - WGS

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#239]
**Issue**
#208 introduced a `depth_of_coverage` step part that computes the DoC using [maelstrom-core](https://github.com/bihealth/maelstrom-core) for WGS. It was enabled by default in `DEFAULT_CONFIG` which leads to issues for WES projects.

```
step_config:
  ngs_mapping:
    ...
    bam_collect_doc:
      enabled: true
      window_length: 1000
```

**Additional context**
Original issue: #206
