### ISSUE TITLE
External BAM QC step can't handle cohorts with multiple library kits

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#244]
**Background**
The workflow `variant_export_external` was first implemented to deal with CADS data, an homogeneous source. Hence, the default configuration only accepts one BED file to perform coverage analysis. This limitation becomes a problem when the external data has multiple library kits in the cohort.

```
step_config:
  variant_export_external:
     ...
    target_coverage_report:
      # Mapping from enrichment kit to target region BED file, for either computing per target
      # region coverage or selecting targeted exons. Only used if 'bam_available_flag' is True.
      # It will not generated detailed reporting.
      path_targets_bed: OPTIONAL
```

**Possible solution**
Implement a solution similar to `ngs_mapping` and account for library kit use for sample:
```
step_config:
  ngs_mapping:
   ...
    target_coverage_report:
      # Mapping from enrichment kit to target region BED file, for either computing per--target
      # region coverage or selecting targeted exons.
      #
      # The following will match both the stock IDT library kit and the ones
      # with spike-ins seen from Yale genomics.  The path above would be
      # mapped to the name "default".
      # - name: IDT_xGen_V1_0
      #   pattern: "xGen Exome Research Panel V1\\.0*"
      #   path: "path/to/targets.bed"
      path_target_interval_list_mapping: []
```

**Alternatives**
None.

**Additional context**
Original PR: https://github.com/bihealth/snappy-pipeline/pull/216
