### ISSUE TITLE
Required fields are not marked in workflows

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#249]
**Issues**
Clearly required fields are not properly tagged in some workflows `DEFAULT_CONFIG`.
From `variant_calling`:
```
step_config:
  variant_calling:
    ...
    tools: ['gatk_ug']
```

From `wgs_sv_calling`:
```
step_config:
  wgs_sv_calling:
    tools:
      dna:  # short
      - delly2
      dna_long:  # PacBio/Oxford Nanopore
      - sniffles
```

**To Reproduce**
1. Create new project and steps:
```bash
snappy-start-project --directory new_project --step variant_calling wgs_sv_calling
```
2. See `.snappy_pipeline/config.yaml` , tool information is missing.

**Expected behavior**
The entries in the configure should be explicitly required, even if a default is provided.

**Additional context**
None.
