### ISSUE TITLE
Make check for BWA/STAR index dynamic

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/snappy-pipeline#27]
**Is your feature request related to a problem? Please describe.**
Currently, the ngs_mapping/bwa/path_index attribute always needs to be filled in in the config.yaml, even if the project only includes RNA libs. And similarly, as of some recent updates the star index must be specified even if the project only includes DNA libs.

**Describe the solution you'd like**
_The purpose of this ticket is to make the code smarter, and only check if the index path exists when applicable._

Details of the lib type(s) included in the project will come from the **biomedsheets tsv file**.  
(In the interest of not overly complicating things we'll use the entire contents of the sheet, regardless of whether we may only be actively processing a subset of the entries)

**Describe alternatives you've considered**
N/A

**Additional context**
Internal ticket \#79.

**Comment by holtgrewe** [comment]
@eudesbarbosa would be a good ticket to get started

**Comment by holtgrewe** [comment]
Also, the internal ticket has some more discussion.

**Comment by eudesbarbosa** [comment]
Is there an old config version available so we can use for comparison?
Looking in the code it seems like there was an option to skip validation of the step:

```
    def check_config(self):
        """Method checks that all parameters required to execute BWA are present in the
        configuration. It further checks that the provided index has all the expected file
        extensions. If invalid configuration, it raises InvalidConfiguration exception.
        """
        if "star" not in self.config["tools"]["rna"]:
            return  # STAR not run, don't check configuration  # pragma: no cover
        ...
```

...but that doesn't seem to correspond to current config structure:

```
step_config:
  ngs_mapping:
    bwa:
      path_index: <PATH_TO_BWA_INDEX>
      num_threads_align: 16
    star:
      path_index: <PATH_TO_STAR_INDEX>
```

**Comment by holtgrewe** [comment]
The structure is visible in the defaults.

https://github.com/bihealth/snappy-pipeline/blob/master/snappy_pipeline/workflows/ngs_mapping/__init__.py#L322

**Comment by eudesbarbosa** [comment]
Is solving the problem on the config level an acceptable solution?

This works already (plus, it is consistent with the other steps config structure):
```
step_config:
  ngs_mapping:
    tools:
      dna:
      - bwa
    bwa:
      path_index: /fast/projects/cubit/20.05/static_data/precomputed/BWA/0.7.17/GRCh37/hs37d5/hs37d5.fa
      num_threads_align: 16
   # star:
   #  path_index: /fast/projects/cubit/20.05/static_data/precomputed/STAR/2.7.3a/default/GRCh37/hs37/none
```
