### ISSUE TITLE
Add genome/reference definition section to configuration

### ISSUE THREAD

**Issue by tedil** [bihealth/snappy-pipeline#512]
Currently, steps/tools define their own reference naming conventions.
This can lead to incompatibilities between steps, accidentally selecting incorrect references etc.
Unifying the way references are handled could help prevent that.

However, tools sometimes rely on specific aliases. Therefore, we could add support for aliases, something along the lines of:

```yaml
reference:
  name: GRCh38
  aliases:
    - ensembl: GRCh38
    - ucsc: hg38
    - panel_of_normals.purecn: hg38
```

In principle, we could also directly specify the source and release directly, such that the reference sequence can be downloaded (and cached) automatically, e.g. for ensembl:

```yaml
  reference:
    […]
    source:
      ensembl:
        species: homo_sapiens
        release: 111
        build: GRCh38
```

or local:

```yaml
  reference:
    […]
    source:
      local:
        path: /path/to/ref.fasta
        species: homo_sapiens
        release: 111
        build: GRCh38
```
