### ISSUE TITLE
ngs_data_qc - pydantic throws error when parameters for picard are not defined

### ISSUE THREAD

**Issue by mbenary** [bihealth/snappy-pipeline#556]
**Describe the bug**
When running ngs_data_qc only with fastqc then pydantic throws an error which is related to Picard settings.

**To Reproduce**
```
step_config:
  ngs_data_qc:
    tools: [fastqc]
    fastqc: {}
```

`snappy-snake -nrp`
![image](https://github.com/user-attachments/assets/f236ca31-1e04-4e7a-b369-724db0c63e63)

**Expected behavior**
No error should be thrown and fastqc should be able to run.

**Additional context**
In __init__.py Picard needs to be defined independent of the configuration file. A quick workaround is a change in the config:
```
  ngs_data_qc:
    tools: [fastqc]
    picard:
      programs:
        - CollectAlignmentSummaryMetrics
    fastqc: {}
```
