### ISSUE TITLE
Add repeat expansion analysis

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#75]
**New Feature**
Add option to run ExpansionHunter for repeat expansion analysis.

**Desired solution**
For each patient output dictionary with two main keys: 'rep_info', to store the repeat expansion definitions; and 'result', to store the patient's actual result:

```
rep_info:
  HD:
    gene: HTT
    normal_range_start: 6
    normal_range_end: 34
    expansion_range_start: 36
    expansion_range_end: none
    ...

result
  HD:
     value: 30
     explanation: "Normal - repeat expansion HD observed with 30 units. Normal range: 6 - 34. Expansion range: 36+."
```

**Additional info**
ExpansionHunter git: https://github.com/Illumina/ExpansionHunter 
Possible source of ranges of normality/expansion ranges: https://www.cell.com/ajhg/fulltext/S0002-9297(18)30367-7
