### ISSUE TITLE
gCNV pipeline not independent from XHMM configuration

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/snappy-pipeline#92]
**Issue**
In the CNV calling workflow, gCNV pipeline cannot run if XHMM configurations not defined. Specifically, the `path_target_interval_list_mapping` part, example:
```
xhmm:
      path_target_interval_list_mapping:
        - pattern: "Agilent SureSelect Human All Exon V6.*"
          name: "Agilent_SureSelect_Human_All_Exon_V6"
          path: /<PATH>/exome_panel/Agilent/SureSelect_Human_All_Exon_V6_r2/GRCh37/Exons.bed
```
If configuration is not defined, the library kit wildcard is incorrectly assigned in snakemake rule...
expected: `wildcards: library_kit=Agilent_SureSelect_Human_All_Exon_V6`
observed: `wildcards: library_kit=default`

Downstream error:
```
[Mon Dec 13 11:19:10 2021]
rule targeted_seq_cnv_calling_gcnv_preprocess_intervals:
    output: work/gcnv_preprocess_intervals.default/out/gcnv_preprocess_intervals.default.interval_list
    log: work/gcnv_preprocess_intervals.default/log/gcnv_preprocess_intervals.default.log
    jobid: 0
    wildcards: library_kit=default
                   [ ... ]

gatk PreprocessIntervals \
    --bin-length 0 \
    --interval-merging-rule OVERLAPPING_ONLY \
    -R /fast/projects/cubit/20.05/static_data/reference/GRCh37/hs37d5/hs37d5.fa \
    -L REQUIRED_OR_MAPPING \
    -O work/gcnv_preprocess_intervals.default/out/gcnv_preprocess_intervals.default.interval_list

                   [ ... ]

[December 13, 2021 11:19:21 AM CET] org.broadinstitute.hellbender.tools.copynumber.PreprocessIntervals done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=274726912
***********************************************************************

A USER ERROR has occurred: Badly formed genome unclippedLoc: Query interval "REQUIRED_OR_MAPPING" is not valid for this input.

***********************************************************************
Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.
```

**To Reproduce**
Run the `targeted_seq_cnv_calling` workflow with a similar configuration:
```
  targeted_seq_cnv_calling:
    tools: ['gcnv']
    gcnv:
      path_target_interval_list_mapping:
        - pattern: "Agilent SureSelect Human All Exon V6.*"
          name: "Agilent_SureSelect_Human_All_Exon_V6"
          path: /<PATH>/Agilent/SureSelect_Human_All_Exon_V6_r2/GRCh37/Exons.bed
      path_uniquely_mapable_bed: /<PATH>/static_data/db/goldenpath/variable/GRCh37/wgEncodeCrgMapabilityAlign75mer.eq_1.bed.gz
```

**Expected behavior**
Library kit should be correctly defined if only gCNV configuration is provided.

**Additional context**
Problem most likely caused by library to library kit dictionary definitions: [code](https://github.com/bihealth/snappy-pipeline/blob/master/snappy_pipeline/workflows/targeted_seq_cnv_calling/__init__.py#L939)
